version: "3.8"

services:

  backend:
    build: ./backend
    container_name: backend-container
    command: python main.py
#    ports:
#      - 8000:8000

  frontend:
    build: ./frontend
    ports:
      - 5000:5000
    command: python app.py
    environment:
      - "APP_URL=http://backend-container:8000"
    depends_on:
      - backend

